DROP TABLE IF EXISTS comments, requests, bookings, items, users;

CREATE TABLE IF NOT EXISTS users
(
    id    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512) UNIQUE                     NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS requests
(
    id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512),
    requester_id INT                                  NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_requests_requester_id FOREIGN KEY (requester_id) REFERENCES users (id)
    );

CREATE TABLE IF NOT EXISTS items
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    owner_id    INT                                  NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    request_id  INT,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_items_owner_id FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_to_requests FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS bookings
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP                               NOT NULL,
    end_time   TIMESTAMP                               NOT NULL,
    item_id    INT                                  NOT NULL,
    booker_id  INT                                  NOT NULL,
    status     VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_bookings_item_id FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_bookings_booker_id FOREIGN KEY (booker_id) REFERENCES users (id)
    );

CREATE TABLE IF NOT EXISTS comments
(
    id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(1024)                           NOT NULL,
    item_id   INT                                  NOT NULL,
    author_id INT                                  NOT NULL,
    created   TIMESTAMP default current_timestamp,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_item_id FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_comments_author_id FOREIGN KEY (author_id) REFERENCES users (id)
    );